In [61]:
import pandas as pd
import os

In [63]:
folder_list = os.listdir()
folder_list

['.ipynb_checkpoints',
 'result',
 'year',
 '블로그 데이터(150~600).csv',
 '블로그 데이터(600~1200).csv',
 '블로그 데이터(~149).csv',
 '블로그데이터분석.ipynb']

In [65]:
blog_df = pd.DataFrame()
for i in range(3,6):
    df = pd.read_csv(f"./{folder_list[i]}")
    blog_df = pd.concat([blog_df, df])

In [67]:
blog_df

,Unnamed: 0,title,date,content
0,0,중국 여행 준비물 총람,2006. 7. 4. 15:11,여권여권사진이있는면을복사해두자비자비자번호를반드시적어두자해외여행보험조건을확인하자증명사...
1,1,PC가 가전 제품을 삼켰다? 「NEC ValueStar SR VR770/DD」,2006. 1. 26. 15:37,"가가전제품을삼켰다?770타카하시사토시야20051222최근,텔레비전이라고하면액정이나플..."
2,2,전세계 디지털 셋탑박스 시장동향,2006. 2. 13. 16:15,"전세계디지털셋탑박스시장동향1.개요최근디지털기술의발달과다채널,다매체,고속화,그리고서비..."
3,3,부엌과 인공욕조는 예술공간,2006. 3. 5. 12:45,뉴요커홈패션은진화중예술의향기담뿍담긴환경친화적공간으로송영규기자..월풀욕조는이젠싫다.카...
4,4,"[정보]살균, 탈취 기능 강화한 청풍무구 공기청정기 2500 플러스 출시",2006. 3. 17. 11:03,청정환경전문기업청풍대표최윤정..은에어컨사용으로인해환기가쉽지않은여름철을맞이하여살균과탈...
...,...,...,...,...
144,144,가전업계는 지금 '스팀' 돌풍,2006. 11. 2. 12:19,"가전업계는지금스팀돌풍전자신문20060726스팀오븐,스팀전자레인지,스팀세탁기,스팀청소..."
145,145,차세대 HD 디빅스플레이어 RAPSODY N35 출시,2006. 6. 24. 20:23,서울뉴스와이어2006년06월22일다코스테크놀로지대표강철호..는기술이적용된디빅스플레이...
146,146,시간 절약 상품이 뜬다!,2006. 5. 28. 23:05,글이연수선임연구원경제연구원주5일제시행의확대로주말을여행이나취미생활로활용하는사람들이늘면...
147,147,"PC업체 친환경 경영 ""선택아닌 필수""",2006. 9. 24. 13:05,미국개인용컴퓨터제조업체들이갈수록환경을생각해야하는처지에놓이고있다.21일월스트리트저널에...
148,148,DIY조리기구,2006. 5. 26. 19:05,엄마가만들어준요구르트가짱두부.된장등은밥상에거의매일올라오는음식이다.맛도맛이지만건강에더...

In [69]:
# 1. date 컬럼 -> date형태로 변환 2006. 7. 4. 15:11
# blog_df['date'] = pd.to_datetime(blog_df["date"], format = "%Y. %m. %d. %H:%M",errors='coerce')

In [71]:
# 판다스 자체 변환 사용
blog_df['date'] = pd.to_datetime(blog_df["date"], errors='coerce')
blog_df

,Unnamed: 0,title,date,content
0,0,중국 여행 준비물 총람,2006-07-04 15:11:00,여권여권사진이있는면을복사해두자비자비자번호를반드시적어두자해외여행보험조건을확인하자증명사...
1,1,PC가 가전 제품을 삼켰다? 「NEC ValueStar SR VR770/DD」,2006-01-26 15:37:00,"가가전제품을삼켰다?770타카하시사토시야20051222최근,텔레비전이라고하면액정이나플..."
2,2,전세계 디지털 셋탑박스 시장동향,2006-02-13 16:15:00,"전세계디지털셋탑박스시장동향1.개요최근디지털기술의발달과다채널,다매체,고속화,그리고서비..."
3,3,부엌과 인공욕조는 예술공간,2006-03-05 12:45:00,뉴요커홈패션은진화중예술의향기담뿍담긴환경친화적공간으로송영규기자..월풀욕조는이젠싫다.카...
4,4,"[정보]살균, 탈취 기능 강화한 청풍무구 공기청정기 2500 플러스 출시",2006-03-17 11:03:00,청정환경전문기업청풍대표최윤정..은에어컨사용으로인해환기가쉽지않은여름철을맞이하여살균과탈...
...,...,...,...,...
144,144,가전업계는 지금 '스팀' 돌풍,2006-11-02 12:19:00,"가전업계는지금스팀돌풍전자신문20060726스팀오븐,스팀전자레인지,스팀세탁기,스팀청소..."
145,145,차세대 HD 디빅스플레이어 RAPSODY N35 출시,2006-06-24 20:23:00,서울뉴스와이어2006년06월22일다코스테크놀로지대표강철호..는기술이적용된디빅스플레이...
146,146,시간 절약 상품이 뜬다!,2006-05-28 23:05:00,글이연수선임연구원경제연구원주5일제시행의확대로주말을여행이나취미생활로활용하는사람들이늘면...
147,147,"PC업체 친환경 경영 ""선택아닌 필수""",2006-09-24 13:05:00,미국개인용컴퓨터제조업체들이갈수록환경을생각해야하는처지에놓이고있다.21일월스트리트저널에...
148,148,DIY조리기구,2006-05-26 19:05:00,엄마가만들어준요구르트가짱두부.된장등은밥상에거의매일올라오는음식이다.맛도맛이지만건강에더...

In [49]:
# 년도별로 분리해서 저장 
for i in range (2004, 2025):
    temp_df = blog_df.loc[blog_df['date'].dt.year == i ]
    temp_df.to_csv(f'./year/blog_{i}.csv')

In [51]:
blog_df

,Unnamed: 0,title,date,content
0,0,중국 여행 준비물 총람,2006-07-04 15:11:00,여권여권사진이있는면을복사해두자비자비자번호를반드시적어두자해외여행보험조건을확인하자증명사...
1,1,PC가 가전 제품을 삼켰다? 「NEC ValueStar SR VR770/DD」,2006-01-26 15:37:00,"가가전제품을삼켰다?770타카하시사토시야20051222최근,텔레비전이라고하면액정이나플..."
2,2,전세계 디지털 셋탑박스 시장동향,2006-02-13 16:15:00,"전세계디지털셋탑박스시장동향1.개요최근디지털기술의발달과다채널,다매체,고속화,그리고서비..."
3,3,부엌과 인공욕조는 예술공간,2006-03-05 12:45:00,뉴요커홈패션은진화중예술의향기담뿍담긴환경친화적공간으로송영규기자..월풀욕조는이젠싫다.카...
4,4,"[정보]살균, 탈취 기능 강화한 청풍무구 공기청정기 2500 플러스 출시",2006-03-17 11:03:00,청정환경전문기업청풍대표최윤정..은에어컨사용으로인해환기가쉽지않은여름철을맞이하여살균과탈...
...,...,...,...,...
144,144,가전업계는 지금 '스팀' 돌풍,2006-11-02 12:19:00,"가전업계는지금스팀돌풍전자신문20060726스팀오븐,스팀전자레인지,스팀세탁기,스팀청소..."
145,145,차세대 HD 디빅스플레이어 RAPSODY N35 출시,2006-06-24 20:23:00,서울뉴스와이어2006년06월22일다코스테크놀로지대표강철호..는기술이적용된디빅스플레이...
146,146,시간 절약 상품이 뜬다!,2006-05-28 23:05:00,글이연수선임연구원경제연구원주5일제시행의확대로주말을여행이나취미생활로활용하는사람들이늘면...
147,147,"PC업체 친환경 경영 ""선택아닌 필수""",2006-09-24 13:05:00,미국개인용컴퓨터제조업체들이갈수록환경을생각해야하는처지에놓이고있다.21일월스트리트저널에...
148,148,DIY조리기구,2006-05-26 19:05:00,엄마가만들어준요구르트가짱두부.된장등은밥상에거의매일올라오는음식이다.맛도맛이지만건강에더...

In [53]:
from kiwipiepy import Kiwi
kiwi = Kiwi()


result_list =[]


# 하나씩 불러와
for i in range (2004, 2025):
    read_df = pd.read_csv(f'./year/blog_{i}.csv')

    # df의 모든 text를 하나의 word로 변환
    combined_word = ' '.join(read_df.astype(str).values.flatten())
    #print("방법 1 결과:", combined_word)a
    
    
    # kiwi로 토큰단위 분리
    result = kiwi.tokenize(combined_word)
    
    
    # 일반명사, 고유명사만 리스트에 저장
    noun_list = []
    
    for token in result:
        if token.tag in ['NNG','NNP']:
            noun_list.append(token.form)
    
    
    # 단어의 빈도를 카운팅 해주는 도구
    
    from collections import Counter
    
    counter = Counter(noun_list)
    
    # 텍스트 데이터 전처리
    # 상위 100개의 단어만 추출
    top_100_noun_list = counter.most_common(200)
    
    # 2글자 이상의 단어만 추출
    noun_list2 = []
    
    for noun in top_100_noun_list:
        if len(noun[0]) > 1:
            noun_list2.append(noun)

    result_list.append([noun_list2])

In [54]:
concat_all_df = pd.DataFrame()

for i in range(0,len(result_list)):
    print(f"==============={2004+i}=================")
    print(f"{2004+i}의 데이터입니다.")
    print(result_list[i])
    print("\n\n\n")

    # Flatten을 먼저 처리해줍니다. 
    flattened_data = [item for sublist in result_list[i] for item in sublist]
    df = pd.DataFrame(flattened_data, columns=['keyword', '빈도'])
    concat_all_df = pd.concat([concat_all_df,df ], axis =1)

===============2004=================
2004의 데이터입니다.
[[('제품', 601), ('가구', 517), ('구입', 466), ('가격', 416), ('혼수', 309), ('기능', 290), ('가전', 277), ('시장', 228), ('경우', 210), ('사용', 209), ('디지털', 194), ('가능', 176), ('싱글', 173), ('전자', 152), ('전문', 146), ('선택', 144), ('판매', 144), ('정도', 139), ('다양', 135), ('구매', 132), ('신부', 129), ('냉장고', 123), ('세트', 119), ('상가', 114), ('인기', 113), ('방송', 110), ('브랜드', 109), ('국내', 109), ('거리', 109), ('매장', 108), ('이상', 107), ('사람', 107), ('인터넷', 107), ('필요', 100), ('결혼', 100), ('로봇', 99), ('서비스', 98), ('필수', 96), ('디자인', 94), ('공기', 91), ('세탁기', 90), ('청소', 90), ('생각', 86), ('기술', 84), ('신랑', 82), ('신혼', 81), ('이용', 80), ('고급', 78), ('업체', 78), ('남자', 76), ('일반', 75), ('비교', 75), ('화이트', 73), ('쇼핑', 73), ('가전제품', 72), ('상품', 72), ('정보', 72), ('고객', 71), ('확인', 70), ('할인', 69), ('품목', 67), ('시간', 66), ('위치', 66), ('생활', 65), ('모델', 65), ('먼지', 65), ('그릇', 64), ('편리', 62), ('밥솥', 61), ('침대', 61), ('점포', 60), ('공간', 59), ('방식', 57), ('중요', 57), ('기본', 56), ('시스템', 56), ('백화점', 56), ('전자레인지', 56), ('홈시어터', 55), ('최고', 55), ('방법', 54), ('패키지', 54), ('세계', 53), ('주방', 52), ('전체', 52), ('친구', 52), ('환경', 51), ('대부분', 51), ('매력', 51), ('서랍', 51), ('침구', 51), ('출시', 50), ('부부', 50), ('자신', 50), ('유명', 50), ('최근', 49), ('사랑', 49), ('단지', 48), ('분석', 48), ('예산', 48), ('개발', 48), ('필터', 47), ('하이마트', 47), ('부분', 46), ('고려', 46), ('제공', 46), ('침실', 46), ('가정', 46), ('기업', 46), ('삼성', 45), ('청정기', 45), ('준비', 45), ('인테리어', 44), ('장점', 44), ('청소기', 44), ('기기', 44), ('크기', 44), ('문의', 44), ('소비자', 43), ('쇼핑몰', 43), ('규모', 43), ('전망', 43), ('김치냉장고', 43), ('영상', 42), ('드럼', 42), ('회사', 42), ('조사', 42), ('요리', 42), ('용량', 41), ('세탁', 41), ('분위기', 41), ('채널', 40), ('느낌', 40), ('포인트', 39), ('화면', 39), ('요즘', 39), ('성능', 39), ('제거', 39), ('분야', 39), ('수입', 39), ('소파', 39), ('경쟁', 39), ('여자', 39), ('자동', 38), ('대형', 38), ('단계', 38), ('전자랜드', 38), ('여성', 38), ('이유', 38), ('네트워크', 38), ('각종', 38), ('차이', 37), ('차지', 37), ('시작', 37), ('활용', 37), ('유지', 37), ('품질', 37), ('운영', 37), ('물건', 37), ('전기', 37), ('그릴', 37), ('색상', 36), ('상태', 36), ('예비', 36), ('컴퓨터', 36), ('카메라', 36), ('전략', 36), ('가열', 36), ('섹스', 36), ('서울', 36), ('공장', 36), ('삼성전자', 35), ('자리', 35), ('포함', 35), ('테크노마트', 35), ('성장', 35), ('미국', 35), ('용품', 35), ('가스', 35), ('특징', 34), ('산업', 34)]]




===============2005=================
2005의 데이터입니다.
[[('제품', 392), ('사용', 191), ('기능', 165), ('가전', 130), ('공기', 127), ('경우', 125), ('세탁기', 125), ('구입', 125), ('정도', 110), ('시장', 107), ('기업', 97), ('기술', 95), ('세탁', 93), ('가격', 91), ('냉장고', 82), ('필요', 82), ('방식', 81), ('필터', 78), ('일본', 77), ('필수', 76), ('일반', 76), ('선택', 74), ('청정기', 72), ('한국', 71), ('시간', 71), ('판매', 70), ('이상', 70), ('가전제품', 67), ('가능', 67), ('전자', 64), ('청소', 61), ('청소기', 61), ('성능', 60), ('용량', 60), ('업체', 57), ('특허', 57), ('가구', 56), ('관련', 55), ('확인', 54), ('플레이어', 52), ('드럼', 52), ('편리', 52), ('로봇', 52), ('공간', 50), ('전기', 50), ('디지털', 48), ('인터넷', 48), ('이용', 48), ('기기', 48), ('김치', 47), ('전략', 47), ('살균', 47), ('구매', 46), ('사람', 46), ('구조', 45), ('국내', 44), ('경쟁', 44), ('소비', 44), ('소비자', 44), ('상품', 43), ('온도', 43), ('결정', 42), ('발생', 41), ('다양', 40), ('생각', 40), ('먼지', 40), ('커피', 39), ('변화', 38), ('중요', 38), ('강화', 37), ('세계', 37), ('부품', 37), ('제거', 37), ('개발', 37), ('세균', 36), ('고려', 35), ('활용', 35), ('설치', 35), ('가정', 34), ('요리', 34), ('회사', 34), ('보관', 34), ('부분', 33), ('가스', 33), ('비교', 32), ('정보', 32), ('중고', 32), ('분야', 32), ('생활', 31), ('크기', 31), ('소음', 31), ('차이', 31), ('서비스', 31), ('남성', 31), ('에어컨', 30), ('품목', 30), ('체크', 30), ('수준', 30), ('혁신', 30), ('출시', 29), ('매장', 29), ('디자인', 29), ('미국', 29), ('준비', 29), ('실내', 29), ('정수기', 29), ('인기', 29), ('오염', 29), ('올해', 28), ('지난해', 28), ('게임', 28), ('문제', 28), ('확대', 27), ('비용', 27), ('기준', 27), ('내부', 27), ('조절', 27), ('고장', 27), ('주방', 27), ('교체', 26), ('자리', 26), ('고객', 26), ('수명', 26), ('의료', 26), ('산업', 25), ('웰빙', 25), ('중국', 25), ('화질', 25), ('사업', 25), ('물건', 25), ('장점', 25), ('평균', 25), ('뚜껑', 25), ('여성', 25), ('재산', 25), ('모델', 24), ('전문', 24), ('지원', 24), ('부부', 24), ('세트', 24), ('물질', 24), ('시스템', 24), ('효과', 24), ('컴퓨터', 24), ('거실', 24), ('시작', 24), ('성장', 23), ('기존', 23), ('기간', 23), ('밥솥', 23), ('자신', 23), ('우리나라', 23), ('설명', 23), ('야채', 23), ('예상', 22), ('평가', 22), ('기본', 22), ('상태', 22), ('방지', 22), ('김치냉장고', 22), ('단계', 22), ('브랜드', 22), ('우수', 22), ('과정', 22), ('연구', 22), ('고급', 21), ('구분', 21), ('온라인', 21), ('유지', 21), ('저장', 21), ('세상', 21), ('전화', 21), ('표시', 21), ('자체', 21), ('사용량', 21), ('탈수', 21), ('컨텐츠', 21), ('예약', 20), ('처음', 20), ('무선', 20)]]




===============2006=================
2006의 데이터입니다.
[[('제품', 476), ('기능', 331), ('가전', 218), ('시장', 210), ('냉장고', 209), ('김치냉장고', 191), ('브랜드', 189), ('가격', 165), ('구입', 162), ('사용', 156), ('김치', 145), ('디지털', 127), ('보관', 126), ('세탁기', 121), ('디자인', 118), ('경우', 114), ('정도', 113), ('인기', 93), ('기술', 89), ('선택', 88), ('가능', 87), ('박스', 87), ('전자', 84), ('생각', 82), ('필요', 81), ('사람', 76), ('일반', 75), ('다양', 75), ('필수', 74), ('이상', 73), ('이용', 72), ('용량', 72), ('시간', 70), ('업체', 70), ('삼성', 70), ('인터넷', 68), ('스팀', 68), ('중국', 67), ('혼수', 67), ('서비스', 65), ('상품', 65), ('공기', 64), ('공간', 63), ('통합', 63), ('엘지', 62), ('청소', 61), ('청소기', 61), ('방식', 60), ('가구', 60), ('전략', 59), ('로봇', 59), ('가전제품', 58), ('출시', 58), ('생활', 58), ('가정', 57), ('판매', 57), ('삼성전자', 57), ('디오스', 57), ('편리', 56), ('드럼', 56), ('짝퉁', 55), ('최근', 54), ('세계', 54), ('모델', 52), ('차이', 52), ('온도', 52), ('부분', 50), ('활용', 50), ('설명', 50), ('하우젠', 50), ('주방', 50), ('쇼핑', 49), ('구매', 49), ('거실', 48), ('제공', 48), ('전기', 48), ('백화점', 48), ('고급', 47), ('매장', 47), ('효과', 45), ('소비자', 44), ('컬러', 44), ('건조', 44), ('기본', 42), ('기업', 42), ('적용', 41), ('인도', 41), ('사진', 39), ('대신', 39), ('관리', 39), ('자리', 39), ('직원', 38), ('냉장', 38), ('회사', 37), ('비교', 37), ('고객', 37), ('성장', 37), ('오븐', 37), ('저장', 37), ('확인', 36), ('전망', 36), ('신혼', 36), ('비디오', 35), ('내장', 35), ('방송', 35), ('개발', 35), ('업계', 35), ('명품', 35), ('이유', 34), ('할인', 34), ('유지', 34), ('문제', 34), ('필터', 34), ('장점', 34), ('식품', 34), ('소형', 33), ('상태', 33), ('제조', 33), ('성능', 33), ('환경', 33), ('요즘', 33), ('하이마트', 33), ('특징', 33), ('조절', 32), ('기존', 32), ('문화', 32), ('비용', 32), ('구조', 31), ('계획', 31), ('문형', 31), ('청정기', 30), ('먼지', 30), ('맞벌이', 30), ('서랍', 30), ('특허', 30), ('정리', 29), ('중심', 29), ('지원', 29), ('크기', 29), ('화질', 29), ('웰빙', 29), ('엄마', 29), ('지펠', 29), ('부부', 29), ('종류', 28), ('세탁', 28), ('내부', 28), ('화면', 28), ('중요', 28), ('올해', 28), ('관련', 28), ('국내', 28), ('강화', 28), ('물건', 28), ('홈쇼핑', 28), ('카드', 27), ('플레이어', 27), ('업그레이드', 27), ('고려', 27), ('규모', 27), ('제거', 27), ('원룸', 27), ('결혼', 27), ('프리미엄', 27), ('각종', 26), ('시스템', 26), ('도입', 26), ('정보', 26), ('추가', 26), ('예상', 26), ('음식', 26), ('숙성', 26), ('베이징', 26), ('식기', 26), ('소음', 25), ('에어컨', 25)]]




===============2007=================
2007의 데이터입니다.
[[('제품', 524), ('기능', 276), ('가전', 238), ('구입', 232), ('가격', 179), ('사용', 171), ('선택', 150), ('디자인', 133), ('오븐', 131), ('시장', 127), ('냉장고', 124), ('정도', 121), ('경우', 119), ('전자', 114), ('수요', 112), ('가전제품', 112), ('혼수', 112), ('필요', 100), ('가능', 100), ('세탁기', 100), ('판매', 91), ('에어컨', 91), ('방식', 88), ('청소', 85), ('인기', 85), ('이상', 84), ('기상', 81), ('스팀', 78), ('생활', 78), ('필수', 72), ('업체', 72), ('주방', 71), ('디지털', 71), ('시간', 71), ('상품', 71), ('부부', 70), ('확인', 69), ('용량', 68), ('소비자', 67), ('이용', 67), ('다양', 67), ('공기', 66), ('중요', 66), ('사람', 64), ('라스베이거스', 64), ('화면', 62), ('생각', 62), ('최근', 61), ('고려', 60), ('시스템', 59), ('브랜드', 56), ('요리', 56), ('성능', 56), ('전기', 55), ('편리', 54), ('김치', 54), ('공간', 54), ('정보', 53), ('일반', 52), ('출시', 52), ('세계', 52), ('김치냉장고', 49), ('신혼', 49), ('투자', 49), ('기술', 49), ('먼지', 49), ('가구', 48), ('삼성전자', 47), ('청소기', 46), ('기기', 45), ('구매', 45), ('할인', 45), ('기본', 44), ('매장', 44), ('시작', 44), ('비교', 44), ('품목', 44), ('드럼', 44), ('가스', 44), ('음식물', 43), ('요인', 42), ('효과', 42), ('화질', 42), ('기업', 42), ('처리', 41), ('국내', 41), ('활용', 41), ('가습기', 40), ('크기', 40), ('만화방', 40), ('가정', 38), ('올해', 38), ('관련', 38), ('만화', 38), ('기대', 37), ('세탁', 37), ('오디오', 37), ('그림', 37), ('각종', 37), ('인터넷', 36), ('기간', 36), ('대형', 36), ('모델', 36), ('레인지', 36), ('보관', 36), ('멀티', 36), ('설치', 35), ('영향', 35), ('패턴', 35), ('한국', 35), ('전자레인지', 34), ('중심', 34), ('결정', 34), ('전문', 34), ('서비스', 33), ('성장', 33), ('신혼부부', 33), ('필터', 33), ('장점', 33), ('방법', 33), ('산업', 33), ('제공', 33), ('유지', 33), ('규모', 33), ('축제', 33), ('코웨이', 32), ('대표', 32), ('밥솥', 32), ('소형', 32), ('조사', 32), ('예비', 32), ('체크', 32), ('행사', 32), ('증가', 31), ('매출', 31), ('다음', 31), ('여름', 31), ('음악', 31), ('제거', 30), ('웅진', 30), ('종류', 30), ('자신', 30), ('경제', 30), ('변화', 30), ('고급', 30), ('추천', 30), ('빌트', 30), ('관심', 29), ('청정기', 29), ('커피', 29), ('계획', 29), ('효율', 29), ('확대', 29), ('석유', 29), ('차지', 28), ('정수기', 28), ('지난해', 28), ('건조', 28), ('음식', 28), ('요즘', 28), ('차이', 28), ('포인트', 28), ('소비', 28), ('디스플레이', 28), ('비용', 28), ('전체', 28), ('조절', 28), ('다리미', 28), ('인테리어', 27), ('자동', 27), ('기존', 27), ('분석', 27), ('플레이어', 27), ('빨래', 27), ('전화기', 27), ('린나이', 26), ('맞벌이', 26), ('세척', 26), ('부분', 26)]]




===============2008=================
2008의 데이터입니다.
[[('제품', 343), ('가전', 210), ('기능', 210), ('사용', 152), ('구입', 145), ('가격', 141), ('공기', 139), ('에어컨', 116), ('경우', 112), ('혼수', 108), ('세탁기', 105), ('시장', 105), ('필터', 100), ('디자인', 97), ('정도', 94), ('전자', 92), ('오븐', 91), ('필요', 87), ('청정기', 85), ('냉장고', 84), ('인기', 80), ('필수', 78), ('시간', 76), ('방식', 72), ('와인', 67), ('일반', 64), ('게임', 64), ('디지털', 63), ('스팀', 63), ('할인', 60), ('청소', 60), ('판매', 60), ('소비자', 59), ('전기', 59), ('처리', 57), ('먼지', 57), ('음식물', 56), ('가능', 56), ('가전제품', 56), ('청소기', 55), ('다양', 54), ('선택', 52), ('이상', 51), ('제거', 50), ('드럼', 49), ('편리', 46), ('구매', 45), ('요즘', 44), ('출시', 44), ('생활', 43), ('이용', 43), ('국내', 43), ('건조', 41), ('생각', 40), ('환경', 40), ('여성', 40), ('시스템', 40), ('보관', 39), ('기존', 38), ('한국', 38), ('살균', 38), ('발생', 38), ('품목', 37), ('세탁', 37), ('주부', 37), ('올해', 37), ('확인', 37), ('가스', 37), ('브랜드', 36), ('독일', 36), ('업체', 35), ('기기', 35), ('기업', 35), ('관리', 34), ('업계', 34), ('기술', 34), ('소음', 34), ('에너지', 34), ('선호', 33), ('모델', 33), ('주방', 33), ('부부', 33), ('설치', 33), ('음식', 32), ('효과', 32), ('사람', 32), ('김치냉장고', 31), ('소비', 31), ('예비', 30), ('비용', 30), ('매장', 30), ('중요', 30), ('성장', 30), ('삼성전자', 30), ('결혼', 30), ('전력', 30), ('비교', 29), ('케어', 29), ('방법', 29), ('콘솔', 29), ('컴퓨터', 28), ('단계', 28), ('셀러', 28), ('용량', 27), ('대비', 27), ('요리', 26), ('가정', 26), ('성능', 26), ('인테리어', 26), ('냄새', 26), ('매출', 26), ('공간', 25), ('크기', 25), ('증가', 25), ('미세', 25), ('물질', 25), ('필립스', 25), ('신혼', 24), ('조리', 24), ('대표', 24), ('리뷰', 24), ('안심', 24), ('주전자', 24), ('트랜스', 24), ('기준', 23), ('전문', 23), ('멀티', 23), ('고급', 23), ('유지', 23), ('온도', 23), ('소형', 23), ('추가', 23), ('혜택', 23), ('쇼핑', 22), ('트렌드', 22), ('온라인', 22), ('고려', 22), ('추천', 22), ('관련', 22), ('최대', 22), ('상품', 22), ('개발', 22), ('조사', 21), ('장점', 21), ('교체', 21), ('각종', 21), ('용품', 21), ('지난해', 21), ('식기', 21), ('정화', 21), ('자동', 21), ('전망', 21), ('절약', 21), ('프리미엄', 20), ('실내', 20), ('안전', 20), ('세계', 20), ('전체', 20), ('부분', 20), ('밥솥', 20), ('커피', 20), ('대부분', 20), ('시작', 20), ('효율', 20), ('고객', 20), ('자연', 20), ('컬러', 19), ('김치', 19), ('기본', 19), ('광파', 19), ('여름', 19), ('활용', 19), ('시즌', 19), ('추세', 19), ('연결', 19), ('보급', 19), ('테크', 19), ('매트리스', 19), ('호주', 19), ('비데', 18)]]




===============2009=================
2009의 데이터입니다.
[[('제품', 248), ('가전', 227), ('사용', 203), ('후드', 195), ('김치', 184), ('주방', 160), ('기능', 156), ('공기', 152), ('에너지', 139), ('청소', 104), ('김치냉장고', 101), ('건강', 97), ('하츠', 96), ('가능', 91), ('교체', 90), ('냉장고', 89), ('시장', 85), ('필수', 84), ('청정기', 78), ('가스', 75), ('청소기', 74), ('필요', 68), ('효과', 67), ('가전제품', 67), ('발생', 66), ('디자인', 65), ('요리', 65), ('온도', 65), ('환경', 65), ('설치', 64), ('소비', 64), ('지펠', 63), ('필터', 62), ('세탁기', 61), ('시간', 58), ('보관', 57), ('관리', 57), ('패시브', 57), ('혼수', 56), ('경우', 53), ('먼지', 53), ('절약', 53), ('성능', 51), ('기존', 51), ('이상', 49), ('하우스', 48), ('적용', 47), ('유해', 47), ('전기', 46), ('중국', 46), ('건조', 45), ('실내', 45), ('에어컨', 44), ('선택', 44), ('생각', 43), ('주부', 43), ('구입', 42), ('개발', 42), ('중요', 41), ('방법', 41), ('관련', 41), ('로봇', 41), ('정도', 40), ('활용', 40), ('생활', 40), ('기업', 40), ('제거', 39), ('전자', 39), ('기술', 39), ('상품', 39), ('인증', 39), ('활성', 39), ('사람', 38), ('전력', 38), ('용량', 38), ('지멘스', 38), ('일반', 38), ('이용', 37), ('물질', 37), ('소비자', 37), ('모델', 36), ('부분', 35), ('다양', 35), ('브랜드', 34), ('세탁', 34), ('이야기', 34), ('확인', 34), ('내부', 34), ('계획', 34), ('편리', 33), ('효율', 33), ('업체', 33), ('선정', 33), ('절감', 32), ('준비', 31), ('음식', 31), ('결혼', 30), ('냄새', 30), ('조절', 30), ('전력량', 30), ('건물', 30), ('기간', 29), ('스마트', 29), ('와인', 29), ('증가', 29), ('문화', 29), ('광주시', 29), ('가정', 28), ('정보', 28), ('요즘', 28), ('인테리어', 28), ('산업', 28), ('연구', 28), ('황사', 28), ('경제', 27), ('가격', 27), ('시스템', 27), ('방식', 27), ('분리', 27), ('국내', 27), ('보급', 27), ('향상', 27), ('사진', 27), ('사업', 27), ('기사', 27), ('건축', 27), ('여성', 27), ('사실', 26), ('성분', 26), ('주요', 26), ('기준', 26), ('결과', 26), ('오염', 26), ('구매', 25), ('전문', 25), ('공간', 25), ('기본', 25), ('인기', 25), ('이웃', 25), ('스타', 25), ('작동', 25), ('확대', 25), ('단열', 25), ('캠페인', 25), ('광주', 25), ('아이', 24), ('해결', 24), ('사랑', 24), ('판매', 24), ('자동', 23), ('이유', 23), ('드럼', 23), ('회사', 23), ('진행', 23), ('홈페이지', 23), ('처리', 23), ('프리미엄', 23), ('비교', 23), ('지원', 23), ('수요', 23), ('전체', 23), ('화질', 23), ('출시', 23), ('리스', 22), ('시작', 22), ('난방', 22), ('원인', 22), ('세계', 22), ('일본', 22), ('생산', 22), ('보더', 21), ('정부', 21), ('체험', 21), ('장점', 21), ('규격', 21), ('이미지', 21), ('창문', 21), ('전망', 21), ('마음', 21), ('추진', 21), ('참여', 21), ('수입', 21), ('산초', 21)]]




===============2010=================
2010의 데이터입니다.
[[('가전', 241), ('제품', 202), ('사용', 175), ('기능', 156), ('냉장고', 118), ('구입', 104), ('전기', 94), ('혼수', 86), ('생각', 83), ('필수', 82), ('공기', 82), ('환경', 82), ('필요', 76), ('가전제품', 74), ('청소', 73), ('세탁기', 73), ('가능', 70), ('오븐', 69), ('경우', 66), ('쿠쿠', 66), ('가격', 64), ('시간', 62), ('디자인', 61), ('가구', 58), ('먼지', 56), ('비용', 56), ('보관', 54), ('구매', 54), ('음식물', 54), ('생활', 53), ('가습기', 53), ('김치냉장고', 51), ('정도', 49), ('김치', 49), ('선택', 49), ('이상', 48), ('냄새', 48), ('에어컨', 46), ('결혼', 45), ('블랙', 45), ('주방', 43), ('준비', 42), ('업체', 42), ('덱스터', 42), ('방법', 41), ('요즘', 41), ('딤채', 41), ('확인', 41), ('온도', 40), ('지출', 39), ('실내', 38), ('아이', 38), ('필터', 37), ('히터', 37), ('커피', 37), ('부분', 36), ('방식', 35), ('처리', 35), ('제거', 34), ('설치', 34), ('체크', 34), ('청정기', 33), ('이사', 33), ('가정', 33), ('일반', 32), ('다양', 32), ('피부', 32), ('삼성', 32), ('청소기', 31), ('건강', 31), ('쓰레기', 31), ('요리', 30), ('발생', 30), ('살균', 30), ('감사', 30), ('기술', 30), ('컬러', 30), ('전력', 29), ('조절', 29), ('하이마트', 29), ('시즌', 29), ('추천', 28), ('소비', 28), ('활용', 28), ('신혼', 28), ('밥솥', 28), ('부부', 28), ('비교', 27), ('사람', 26), ('스마트', 26), ('인기', 26), ('전체', 26), ('리베', 26), ('자동', 25), ('곰팡이', 25), ('유지', 25), ('습도', 25), ('고려', 25), ('걱정', 25), ('중요', 25), ('소비자', 25), ('겨울', 24), ('편리', 24), ('지펠', 24), ('이용', 24), ('살림', 23), ('내부', 23), ('동안', 23), ('공간', 23), ('판매', 23), ('추가', 23), ('할인', 23), ('문제', 23), ('매장', 22), ('품목', 22), ('모션', 22), ('시민', 22), ('산업', 22), ('소형', 21), ('색상', 21), ('가스', 21), ('미니', 21), ('예비', 21), ('사항', 21), ('상태', 20), ('건조', 20), ('출시', 20), ('전자', 20), ('에너지', 20), ('스팀', 20), ('신부', 20), ('물질', 20), ('상품', 20), ('작동', 19), ('오염', 19), ('장점', 19), ('시스템', 19), ('적용', 19), ('용량', 19), ('음식', 19), ('절약', 19), ('아파트', 19), ('포장', 18), ('전문', 18), ('기본', 18), ('이유', 18), ('대비', 18), ('맞벌이', 18), ('브랜드', 18), ('진행', 18), ('보호', 18), ('감기', 18), ('자리', 17), ('분리', 17), ('가족', 17), ('효과', 17), ('용기', 17), ('선물', 17), ('세련', 17), ('인테리어', 17), ('반찬', 17), ('주부', 16), ('시작', 16), ('사실', 16), ('정보', 16), ('모델', 16), ('포함', 16), ('안전', 16), ('요금', 16), ('각종', 16), ('세탁', 16), ('위생', 16), ('고급', 16), ('제공', 16), ('버튼', 16)]]




===============2011=================
2011의 데이터입니다.
[[('가전', 418), ('혼수', 220), ('스마트', 191), ('음식물', 190), ('제품', 184), ('냉장고', 142), ('기능', 132), ('쓰레기', 129), ('주방', 128), ('사용', 128), ('처리', 112), ('세탁기', 102), ('오븐', 96), ('필수', 94), ('가전제품', 80), ('디자인', 74), ('필요', 73), ('구입', 70), ('준비', 65), ('하이마트', 64), ('결혼', 61), ('전자', 59), ('가격', 59), ('설치', 58), ('청소기', 58), ('가능', 57), ('시간', 57), ('삼성', 57), ('다양', 56), ('요리', 56), ('공기', 53), ('구매', 53), ('청소', 51), ('전기', 50), ('마니아', 50), ('선물', 49), ('생각', 48), ('지펠', 47), ('경우', 45), ('정수기', 44), ('정도', 43), ('부부', 43), ('커피', 43), ('선택', 42), ('신혼', 42), ('이용', 41), ('생활', 40), ('이벤트', 40), ('카페', 39), ('버튼', 36), ('편리', 36), ('비교', 36), ('필터', 36), ('브랜드', 36), ('건조', 35), ('걱정', 35), ('정보', 35), ('이상', 34), ('추천', 34), ('작동', 34), ('고민', 34), ('빨래', 33), ('냄새', 33), ('요구르트', 33), ('살균', 32), ('요즘', 32), ('라이프', 32), ('아이', 31), ('확인', 31), ('환경', 31), ('제거', 31), ('밥솥', 31), ('세탁', 30), ('결정', 30), ('건강', 30), ('소형', 29), ('시작', 29), ('이제', 28), ('공간', 27), ('기존', 27), ('클릭', 27), ('음식', 27), ('에너지', 27), ('일반', 27), ('다이어트', 27), ('에어컨', 27), ('오피스텔', 27), ('활용', 26), ('로봇', 26), ('혜택', 26), ('온도', 26), ('디지털', 26), ('신혼부부', 26), ('보관', 25), ('용량', 25), ('제습기', 25), ('방식', 25), ('친구', 25), ('관리', 25), ('김치냉장고', 25), ('알뜰', 25), ('조절', 24), ('습기', 24), ('주부', 24), ('효율', 24), ('먼지', 24), ('모델', 24), ('생산', 24), ('성능', 23), ('적용', 23), ('여름', 23), ('최고', 23), ('시스템', 23), ('품목', 23), ('인기', 22), ('전력', 22), ('집안', 22), ('마음', 22), ('에어', 22), ('신부', 22), ('자동', 21), ('청정기', 21), ('실속', 21), ('서비스', 21), ('스마트폰', 21), ('상품', 20), ('삼성전자', 20), ('고급', 20), ('아이템', 20), ('매장', 20), ('기술', 20), ('디오스', 20), ('식품', 20), ('이야기', 19), ('사람', 19), ('소비', 19), ('압력', 19), ('스팀', 19), ('방사능', 19), ('이사', 18), ('검색', 18), ('장마철', 18), ('바람', 18), ('절전', 18), ('국내', 18), ('해결', 18), ('가족', 18), ('리스트', 18), ('가구', 17), ('세균', 17), ('식사', 17), ('부분', 17), ('동생', 17), ('사실', 17), ('최대', 17), ('할인', 17), ('드럼', 17), ('절약', 17), ('소비자', 16), ('사랑', 16), ('쿠쿠', 16), ('아침', 16), ('조리', 16), ('부담', 16), ('이번', 16), ('습도', 16), ('소개', 16), ('자리', 16), ('기름', 16), ('장만', 16), ('동양매직', 16), ('머신', 16), ('중국', 16), ('장점', 15), ('보온', 15), ('종류', 15), ('재생', 15), ('분리', 15)]]




===============2012=================
2012의 데이터입니다.

In [59]:
concat_all_df.to_excel("./result/blog_concat_df.xlsx", index = False)